### ISSUE TITLE
Provide output to StringBuilder

### ISSUE THREAD

**Issue by Alex-ABPerson** [EamonNerbonne/ExpressionToCode#216]
One feature that would be extremely useful, especially for situations where this is called upon thousands of times, would be the ability to have it directly write the generated code into a `StringBuilder` provided by the user. Right now it only returns a `string`, and it allocates an entirely new `StringBuilder` and `string` every single time you use it, and _as far as I can tell_ there is no way to get around this. 

The overhead of those allocations, as well as the overhead of having to _copy_ the contents of `StringBuilder` into the `string` every time, is not ideal for heavy use, especially considering it can be _so easily_ avoided by simply providing the ability to the user to have it write to a `StringBuilder`.

I'm in a situation where I'm planning on using this as part of a source generator and making it responsible for converting lots of smaller sub-expressions of a much larger code block into C# code. And I'm going to be building up this much larger code block with a `StringBuilder`, and it would be a huge performance drawback to be constantly creating all these `strings` only for them to be _immediately_ dumped into a `StringBuilder`.

**Comment by EamonNerbonne** [comment]
After much delay and uncertainty, I'm going to prioritize having a minimal API over a potential performance boost, at least until there's a specific, measurable scenario demonstrating that this perf advantage actually matters.
