### ISSUE TITLE
Include variable values in generated code

### ISSUE THREAD

**Issue by girlpunk** [EamonNerbonne/ExpressionToCode#243]
Is it possible to get ExpressionToCode to include values of variables in the code it generates?

For example:

```csharp
// Obviously in a real-world situation these would be coming from something a bit more complex
var a = 1;
var b = 2;

var expression = () => a + b;
return ExpressionToCode.ToCode(expression);
```

This currently returns
```csharp
() => a + b
```
Which is correct, but loses the captured variables. I would like to get something line this:
```csharp
() => 1 + 2
```

**Comment by EamonNerbonne** [comment]
This isn't what you want?

```C#
var a = 1;
var b = 2;

Console.WriteLine(ExpressionToCode.AnnotatedToCode(() => a + b));
```

prints:


```
() => a + b
a + b   →   3
    a   →   1
    b   →   2
```

**Comment by girlpunk** [comment]
Unfortunately those don't fit my use case as they're no longer valid expressions. Apologies, I should have mentioned this requirement originally.

A little more background on what I'm trying to achieve in case it's useful, essentially I'd like to create a JSON file that can be supplied to [RulesEngine](https://github.com/microsoft/RulesEngine). These JSON files contain strings with lambda expressions to be evaluated to check certain conditions, etc.

I have found a workaround, though it's not ideal as it's a bit difficult to implement and rather verbose
```csharp
var a = 1;
var b = 2;

var aExpression = Expression.Constant(a, typeof(int));
var bExpression = Expression.Constant(b, typeof(int));

var addExpression = Expression.Add(aExpression, bExpression);

Console.WriteLine(ExpressionToCode.ToCode(addExpression));
```

**Comment by EamonNerbonne** [comment]
Internally, the library generates a tree of `StringifiedExpression` values that represent substrings of the overall expression with their values.  Those values may or may not be computable (e.g. `x +2` might be 7 if x if 5, x could also be an inner lambda's argument with no value).

If you want to generate a string from such a tree, I just concat the text content - but it'd be fairly easy to instead conditionally replace that text by a string-representation of its value, I'm fairly sure.

However, the question is what that condition is.  Why wouldn't in your example the engine just print 3?  Or, to rephrase: why not simply always print the stringification of the top-level value?

**Comment by girlpunk** [comment]
My original reasoning was that the expression's output would change depending on the environment/OS/host it was run on, however I now realise that this approach could never work as ExpressionToCode wouldn't be able to identify which variables to make static and which come from the environment.

**Comment by EamonNerbonne** [comment]
I'm not opposed to making any of this configurable, to be clear - but yeah, it's not obvious to see how you could use that easily enough to make it worth it.  One reasonable implementation might be to allow stringification to use the runtime value rather than the expression whenever available, and then to stringify not something like `() => a + b * c`, but rather `(a, c) => a + b * c` - because that way it's clear by construction which parts of the expression need to be represented by value, and which by expression.
