### ISSUE TITLE
Lambda Invoke is converted without explicit delegate type

### ISSUE THREAD

**Issue by dadhi** [EamonNerbonne/ExpressionToCode#26]
Test better than words. Currently fails:

    [Test, Explicit("Not working in ExpressionToCode v1.4.7.0")]
    public void Lambda_invoke_converted_without_delegate_type()
    {
        Expression<Func<int>> expr = () => new Func<int>(() => 1)();
            
        var code = ExpressionToCode.ToCode(expr);

        Assert.AreNotEqual(code, "() => (() => 1)()");                   // the code won't compile
        Assert.AreEqual(code, "() => new Func<int>(() => 1)()"); // should be the following
    }

**Comment by EamonNerbonne** [comment]
Thanks for the fix!
