### ISSUE TITLE
Add options parameter to generate full namespaces.

### ISSUE THREAD

**Issue by asd-and-Rizzo** [EamonNerbonne/ExpressionToCode#29]
1. I have ()=> new N1.C()
2. And ()=> new N2.C();
3. I generate code for them and put into code of class which uses both delegates.
Actual: Error cause 2 classes have same names and same code is generated for them `()=> new C()`
Expected: I can ask generation to prefix all static calls and `new` with namespace.

**Comment by EamonNerbonne** [comment]
Yeah, I think I need something like this.

Frankly, I don't want an options *parameter*, I want to make Expression to code a non-static method on an instance that happens to describe the currently selected options.

**Comment by EamonNerbonne** [comment]
This is implemented in #42.  The API is not yet finalized, however.
