### ISSUE TITLE
Renames project and assemblies and namespaces to more .NET standards

### ISSUE THREAD

**Issue by asd-and-Rizzo** [EamonNerbonne/ExpressionToCode#30]
ExpressionToCodeTest to ExpressionToCode.Tests. This is needed to allow ExpressionToCode.Roslyn.Tests uniformity.

ExpressionToCodeLib to ExpressionToCode. .dll is dynamic linke LIBrary. Lib is not used in .NET anywhere, not in open source projects either.

**Comment by EamonNerbonne** [comment]
You're entirely right that this name is pretty terrible!

However, name changes are a pretty annoying breaking change. I'll fix the test assembly+namespace (what's the roslyn uniformity you're refering to, incidentally?); but to fix the namespace+assembly+nuget package names of the library itself I'd probably need to create an intermediate package that references the newly minted package - or something.  In any case, I'd hope that nuget upgrades shouldn't break existing consumers (or at least leave them with breakage they can easily fix).

Do you have a suggestion for how to approach this?

While we're at it, I've got to say "ExpressionToCode" isn't a great name to start with...

**Comment by asd-and-Rizzo** [comment]
I think it is good to generate Roslyn Syntax Tree out of Expressions. I expected it named MainLibName.Roslyn. And this needs MainLibName.Roslyn.Test. But as of now ExpressionToCod`eT`est has no dot. And I think that MainLibNameRoslynTest is bad possible name. It is important not only from style, but also because some builders match test libs with *.Test or more frequently ***.Tests**. Just style of .NET project I have seen so far.

Try this `Eamon.Linq.Expressions.Converters` for assembly name, for integration with Roslyn it will be 'Eamon.Linq.Expressions.Converters.Roslyn'. For all cases use one namespace `Eamon.Linq.Expressions.Converters` or even 'Eamon.Linq.Expressions'(this may be good for some parts which will appear do generic Expression stuff) so any new lib will mixin code when references added (this is how .NET BCL designed and named). 

Regarding backward compatibility, consider next. Search internet for examples of usage 'TypeForwardedTo'. It seems you may create new assembly with previous assembly containing dummy declarations. Both can live in same nuget package for some time I hope, not need to rename package.

Or when you will do some breaking changes only then rename and create new package.
