### ISSUE TITLE
Dump Expression assembly references while dump

### ISSUE THREAD

**Issue by asd-and-Rizzo** [EamonNerbonne/ExpressionToCode#31]
1. I have dumped expression to code.
2. I want to put it into C# class and compile
3. I need add references to assemblies expression references.
   Actual: I have to check this manually.
   Expected: expression already knows all it references, should preserve and reuse.
   Value: If  tocode tree of modern DI container it will reference dozen of assemblies, if want to compile this code into assembly with static factory class - need all references back.
   Value: Right now I added hack to get Roslyn Syntax tree for Code. What if I want to compile it after wrapping to class. Earlier, people where limited with Expression but fast, or unlimited fast with IL but complex and not so secure , or not limited by CodeDom but terribly slow and not good runtime. With Roslyn Syntax Tree and its compilation new  option is provided for Expression users still having good performance, but need migration with all metadata preserved.

**Comment by EamonNerbonne** [comment]
Extracting all the required assembly references shouldn't be terribly complex - You'd need another expression tree walker to determine the assembly of all referenced types.  There are a bunch of cases to handle, sure, but they're pretty much all trivial - methods reference the type they're in, parameters have a declared type (as to variables and member initializations) etc.

Finally, all types can be mapped to their assemblies (and the assemblies of their base types).

You'd also need to do a similar walk for namespace imports.

**Comment by EamonNerbonne** [comment]
I don't think this is super complex, but it's not an hours work either - I don't have time to put it together right now, but I'd be sure to accept a pull request.

I'd recommend starting with an as simple as possible case, initially - just the namespaces, say (since that's less complex).

Alternatively, we could implement a mapping to a roslyn AST, and then do the work there.  The advantage to that approach is that that AST is more powerful, and it's probably more suited for such things anyhow.  However, it's also more complex too...

**Comment by asd-and-Rizzo** [comment]
I found one Roslyn AST to be Syntax only, so all info about types is dropped, may be there is kind of object Tag for each node to store some type info, but I doubt. There are other trees I think to search which a created out of Syntax when assembly references given to compilation unit aftre binding, but not found these yet. 

But its clear about current visitor.

**Comment by asd-and-Rizzo** [comment]
I found that next classes in Roslyn may lead to something similar to Expressions tree(i.e. pertaing type binding info for compilation instead of dropping them like SyntaxTree does, and Expressions  seems language agnostic ): Binder, SematnciModel, BoundExpression. 

These are not so public and not sure how to build these directly, but it may be best options instead of dump references - cause all references will be in Roslyn Tree.

**Comment by EamonNerbonne** [comment]
What do you mean by "not so public"?

**Comment by asd-and-Rizzo** [comment]
Internal and/or not yet documented.
