### ISSUE TITLE
ToValuedCode results into "expression.Name = somevalue"

### ISSUE THREAD

**Issue by asd-and-Rizzo** [EamonNerbonne/ExpressionToCode#33]
I have next code in custom classes:

``` csharp
 [Test]
        public void Array_ToName()
        {
            var arr = new int[]{1};
            var actual = ExpressIt.ToValuedCode(() => arr.Length);
            actual.ShouldBeEquivalentTo("arr.Length = 1");
        }
```

Used to streamline coding of next kind of code:

``` csharp
Console.WriteLine(string.Format("instance.Property1 = {0}",instance.Property1));
```

Expression is slower to run, but faster to type, which often OK when doing some quick research or prototype or test.

Annotated not so good when one line is expected.

Seems fits to ExpresssionToCode additionally to ToAnnotatedCode? So I may start to port code here?

See what I'd like to be in one this lib for simple reuse https://github.com/OpenSharp/ExprSharp/blob/master/src/ExprSharp/ExpressItTests.cs. Skip not related to expressions or already covered by ToCode in some form.

**Comment by EamonNerbonne** [comment]
Sounds like a good idea!

**Comment by EamonNerbonne** [comment]
This is implemented.
