### ISSUE TITLE
ToNameOf similar to https://roslyn.codeplex.com/discussions/570551

### ISSUE THREAD

**Issue by asd-and-Rizzo** [EamonNerbonne/ExpressionToCode#39]
May we discuss here next (from https://github.com/OpenSharp/ExprSharp/tree/master/src/ExprSharp see ExpressItTests and ExtractNameTests):

```
        [Test]
        public void TheProperty_ToNameOf ()
        {
            var actual = ExpressionToCode.ToNameOf (() => TheProperty);
            actual.ShouldBeEquivalentTo("TheProperty");
        }        
```

there is compile time feature for such in C# 6.0(and may not support all expression can), but these several years ahead of now for many developers
https://roslyn.codeplex.com/discussions/570551

Expressions are slow on first call, so not very usable in large scale cause produce long start up of application, but work for prototyping, e.g. UI bindings.

Actually what I'd like to see that `ExpressionToCode` may be ultimate solution do dump things based on expressions with easy accessible static API and what ever structured behind for those who need. 

So I may try argue on Roslyn Issues board with `ExpressionToCode`  for compile time compilation of expressions defined inline in C# text to reduce overhead from several dozens of milliseconds(50 on my PC) for 1-2 on start up. 

About PAssert. Right now it not so usable with large scale unit testing(fine for integration) cause many of unit tests may be 5 ms to run each, but asserting adds 50 ms. 

3000 tests \* 5 ms = 15 sec

15 sec + 3000 tests \* 50 ms =  165 sec

Is may appear `ExpressionToCode` providing methods to infiltrate expression everywhere may provide good ground for compile time compilation of expression with PAssert to work well for many tests runs.

This way expression may provide safe and quite fast metaproramming for C# other languages has.

**Comment by asd-and-Rizzo** [comment]
#39

**Comment by EamonNerbonne** [comment]
Sounds like a good idea.  As to the performance - that's pretty shocking! On my system, 
`Enumerable.Range(0,100000).ForEach(i=>PAssert.That(()=>long.Parse(i.ToString()) == i));` takes 33 seconds, or 0.3ms per assertion.

A college of mine suggested providing a delegate-based implementation with a poor error message that instructs you to switch to the expression version as necessary.

In any case, I'll take a quick peek to see if there's anything I can do about the performance, but I suspect all the time is in `Compile()` i.e. unavoidable overhead.

What we really need in C# is a type that unifies an expression tree and a delegate so we can pick the best of both worlds (that would also make declaring lambdas much easier).

**Comment by EamonNerbonne** [comment]
As an performance experiment I tried using ilspy's code to generate code from a compiled delegate.  This works, and is surprisingly easy, but it's not possible to annotate subexpressions then, and the generated code isn't quite as accurate or compact.  Nevertheless it might be an idea to try...

**Comment by asd-and-Rizzo** [comment]
Other words about IL.

`ILSpy` goes via `Mono.Cecil` which seems does not run on limited/secured like devices) .NET versions. And I guess `Mono.Cecil` references of types are tackled manually while CLR did this for expressions already.

There is other way to access IL via  `System.Reflection.Emit` like here https://github.com/OpenSharp/ExprSharp/blob/master/src/ExprSharp/ExtractName.cs.

May be it faster for `ToNameOf`, but not sure if it supported on limited/secured(like for devices) .NET versions.

Also not sure how to handle overloads, seems may be conflict of `ToXyz(Expression<Action> e)` and `ToXyz(Action e)`.

I hope some  part of `ExpressionToCode`  to run on limited/secured like devices) .NET versions.
