### ISSUE TITLE
Create requirements.md

### ISSUE THREAD

**Issue by asd-and-Rizzo** [EamonNerbonne/ExpressionToCode#56]
For `ToCode`(`ToAnnotadedCode`) as I guess could be :
- convert into valid C# (can parse using Roslyn then)
- can do any expression of any complexity
- customization (like: with and without namespaces; allow not so  valid C# output but pseudocode e.g. when dumping generics; pretty printing; whatever)
- kind of global, e.g. `()=> TheProperty` gives `()=> MyClass.TheProperty`

`ToValuedCode`:
- used to dump some value during debugging or quick check logging (may be left for long in code)
- no need to support big expressions cause `200_length_string_expression = VALUE` not aids debugging or logging
- does not care about `()=>` and omits
- kind of local, `()=> TheProperty` gives `TheProperty = 2`, no class or namespace; 
- kind of local, `()=> this[1]` to `[1] = 2` because we already appended object name identifier to logged sting above

```
myGoodCollection
[1] = 2
[2] = 4
```
- fast when left in logging and called like this

```
for (var o in items){
var sb = new StringBuilder("========" ).
Append(ToValuedCodes(()=> o.Name, ()=> o.P2,()=> o.P2)));
Log(sb);
}
void ToValuedCodes(...){..} // just calls ToValuedCode in loop
```
- seems not so reasonably ported to just call `ToCode`  inside (may be wrong)

`ToName`:
- fast (e.g. when used INPC  in MVVM many times)
- only very short expressions
- work when `nameof` and `[CallerMemberName]` cannot (like we can path expression from INPC implementer passed to base class and to base of base  for several properties differently named) or C# <6
- kind of local,  `()=> MyProperty`  will show `MyProperty`,  `()=> MyMethod(1,2)`  will show `MyMethod`

`ToFullName` if any of usage for this (not sure if there are any direct usage):
- `ToCode`  for `()=> MyMethod(1,2)`  gives  `()=> MyClass.MyMethod(1,2)`, for  `()=> MyMethod(1,2)`.Body gives  `MyClass.MyMethod(1,2)`
- if `ToFullName` for `()=> MyMethod(1,2)` give `MyMethod(p1,p2)` or `MyClass.MyMethod(p1,p2)`? Should parameter/arguments/return types be included?
-  Is any usage of this?

**Comment by asd-and-Rizzo** [comment]
What are real world applications?

- moving away from expressions to compile time code(generate all expressions into code) (like DI containers based on expressions) to support limited .NET versions or improve start up performance.
- logging and debugging
- what about usages in IDEs or `LinqPads` or in T4 templates or during live debugging or other ?
- what aid for charting can be 
```
Chart.Plot(z =>  x * y );
Chart.Plot(() =>  x * y);
```
like here https://github.com/fsharp/FSharpLangDesign/blob/master/FSharp-4.0/AutoQuotationDesignAndSpec.md

**Comment by EamonNerbonne** [comment]
These are great ideas!

**Comment by asd-and-Rizzo** [comment]
I see that ORM or custom data to sql mappings quite use of expressions, obtained names and other stucture.
