### ISSUE TITLE
Alignment wrong with VS2015 testrunner

### ISSUE THREAD

**Issue by markijbema** [EamonNerbonne/ExpressionToCode#58]
When I have a failed test in the VS2015 testrunner, the alignment is totally off. It's already unusable for int comparisons, so I think more complex annotations probably won't work at all.

This might tie into (irl) discussions we had, in which you suggested mentioning the contents of each term might work better. At least in the vs testrunner itself this would surely help a lot.

**Comment by markijbema** [comment]
Screenshot:
![image](https://cloud.githubusercontent.com/assets/624143/9023256/080f3cee-3894-11e5-91a4-d66afaaf9be0.png)

Looking again at it, I think it is placed at the right place, just not as useful when the window isn't very wide.

**Comment by EamonNerbonne** [comment]
The real solution to this is to make the `|` based annotation optional (and not the default).

It would be a lot more useful if it said something like 

`AdditionClass.getMaximumPoints(...): 19`

Particularly for long expressions, this would be a boon.

**Comment by markijbema** [comment]
Agree

**Comment by EamonNerbonne** [comment]
The current alpha (2.0.0-alpha4) has an initial version of the real solution here.  The devil, however, is in the details.

You can now configure which rendering to choose for annotations: 

```C#
var config = ExpressionToCodeConfiguration.DefaultConfiguration.WithAnnotator(CodeAnnotators.SubExpressionPerLineCodeAnnotator);
//either:
config.Assert(() => 1 == 2);
//or:
ExpressionToCodeConfiguration.CurrentConfiguration = config;
PAssert.That(() => 1 == 2);
```

That api might need some tweaking.

So, given a messy expression you'd want to elide:

```C#
var hmm = "1234567890";
PAssert.That(() => hmm[1] == hmm[2] || hmm[4] == hmm[int.Parse(hmm[8].ToString())] || false);
```

You will get the C# and the annotated subexpressions in left-to-right order in the exception message:

```
failed
hmm[1] == hmm[2] || hmm[4] == hmm[int.Parse(hmm[8].ToString())] || false
hmm: "1234567890"
hmm[1]: '2'
hmm[1] == hmm[2]: false
hmm: "1234567890"
hmm[2]: '3'
...[...] == ...[...] || ...[...] == ...[...]: false
hmm: "1234567890"
hmm[4]: '5'
hmm[4] == hmm[int.Parse(...)]: false
hmm: "1234567890"
hmm[int.Parse(....ToString())]: '0'
int.Parse(...[...].ToString()): 9
hmm: "1234567890"
hmm[8]: '9'
hmm[8].ToString(): "9"
```

Clearly, that's not ideal either:

 - there are duplicate entries `hmm: "1234567890"`
 - The left-to-right ordering sounds sane, but you probably actually want something in some conceptual order.  But what?  Bottom-up or top-down?  Depth first or breadth first?
 - Eliding subexpressions is necessary, but this implementation blindly elides after two levels.  That leads to things like `...[...] == ...[...] || ...[...] == ...[...]: false` which is mostly ascii art, but it can also be too much in more usual cases, e.g. `Enumerable.Range((int)... % 100, "asdfasda".Length):  {8, 9, 10, 11, 12, 13, 14, 15}` is probably pushing it.

So, suggestions?

**Comment by EamonNerbonne** [comment]
[ExpressionToCode2alpha4test.zip](https://github.com/EamonNerbonne/ExpressionToCode/files/144997/ExpressionToCode2alpha4test.zip)

Linqpad script of above demo.

**Comment by EamonNerbonne** [comment]
#67 is another variant of the stalks-alternative

**Comment by markijbema** [comment]
did you consider filling in expressions, and evaluating iteratively (in the output), so:

PAssert.That(()=>foo==bar)
PAssert.That()=> "pancake" == "syrup")
PAssert.That() => false)

**Comment by EamonNerbonne** [comment]
Sounds like yet-another alternative.

Doesn't sound too hard to make based on code like that in #71, but I think I'd like to finish that version first.

One thing I'm a little worried about with iterative evaluation is that it works clearly in simple cases, but not so clearly in more complicated ones.  E.g.: embedding objects or values with stringification that isn't valid C#.  I mean, you could "mark up" code with additional symbols to distinguish code from value; sort of like `{}` in a string interpolation (but reversed), but it might turn out tricky.

e.g. 
```
(foo + bar).Length >= 10
(«"maple"» + «"syrup"»).Length >= 10
«"maplesyrup"».Length >= 10
«10» >= 10
«true»
```

Note that that second line is longer than the first, and also that that's likely to be common and unavoidable.  With things like enumerables, that's likely going to become pretty bad.

**Comment by markijbema** [comment]
Yeah it's another alternative. Ideally you'd want interactive output :) Hard to fit interactive inspectable expressions into ascii. I'm not sure if it being longer is a problem; I find that the current problem is more following what's happening, I'm not sure long expressions are a problem per se.

**Comment by EamonNerbonne** [comment]
2.0.0 uses the new, arrow-based layout by default.
