### ISSUE TITLE
Use the FastExpressionCompiler package

### ISSUE THREAD

**Issue by dadhi** [EamonNerbonne/ExpressionToCode#66]
Hi @EamonNerbonne,

I've found some time to make an optimized expression compiler into standalone project as [FastExpressionCompiler](https://github.com/dadhi/FastExpressionCompiler).

Current version is [1.0.0-preview-01](https://www.nuget.org/packages/FastExpressionCompiler/1.0.0-preview-01). But it is pretty stable overall and used in [DryIoc v2](https://bitbucket.org/dadhi/dryioc).

__What was added:__

- Support for .NET Core via NetStandard1.3
- Support for nested lambdas and closures, so the majority of expression types should be covered
- Improved performance :-) as usual

**Comment by EamonNerbonne** [comment]
I'll check it out!

**Comment by EamonNerbonne** [comment]
Incidentally, have you checkout out the optional expression tree interpretation in the .net core bits?  That might be a better fallback for full-compilation for the fast-expression-compiler for some use cases (certainly for unit testing via PAssert)

**Comment by EamonNerbonne** [comment]
Do you have an ETA for non-preview status?  I think I should (finally) release master as a stable version again, so I'd like to avoid preview dependencies short- term.

**Comment by dadhi** [comment]
I think v1 may be released next week. The core is pretty stable and has no found issues. I've released pre1 to get feedback regarding public api, as it may be wider than the one used by DryIoc.

Regarding interpretation, did not check it yet. May be you have the link nearby to share?

**Comment by EamonNerbonne** [comment]
https://docs.microsoft.com/en-us/dotnet/core/api/system.linq.expressions.expression-1#System_Linq_Expressions_Expression_1_Compile_System_Boolean_

which really doesn't tell you anything.

It's not in the .net framework yet(?); only .net core.

Looks like it'll [be in .net standard 2.0](https://github.com/dotnet/standard/pull/76/files), but a correct implementation is trivial by just ignoring the flag, so whether it'll work or merely fall-back to normal compilation is unclear.

**Comment by dadhi** [comment]
Hi @EamonNerbonne ,

FEC preview-02 is out with `&&` and `||` support. Try the benchmark again. I've got 30x perf boost on Compile.

v1 is still planned by EOW.

**Comment by EamonNerbonne** [comment]
Cool!  I'll give it a shot, soon.

**Comment by EamonNerbonne** [comment]
I updated and updated the benchmark.

New results:

```
BenchmarkDotNet=v0.10.3.0, OS=Microsoft Windows NT 6.2.9200.0
Processor=Intel(R) Core(TM) i7-4770K CPU 3.50GHz, ProcessorCount=8
Frequency=3421924 Hz, Resolution=292.2333 ns, Timer=TSC
  [Host]     : Clr 4.0.30319.42000, 64bit RyuJIT-v4.6.1637.0
  DefaultJob : Clr 4.0.30319.42000, 64bit RyuJIT-v4.6.1637.0


                  Method |            Mean |        StdDev |
------------------------ |---------------- |-------------- |
             JustCompile | 411,838.3188 ns | 1,199.1655 ns |
           CompileAndRun | 410,611.0070 ns | 1,124.6116 ns |
         JustFastCompile |  13,860.8841 ns |   344.7677 ns |
       FastCompileAndRun | 209,135.9659 ns |   515.4674 ns |
      PAssertWithCompile | 420,304.9783 ns | 2,280.5607 ns |
  PAssertWithFastCompile | 220,577.7775 ns | 2,419.8266 ns |
 BaseLinePlainLambdaExec |     120.0977 ns |     0.4868 ns |
```

That's pretty nice!

However, it unfortunately also highlights that apparently a significant issue isn't the compilation to IL, it's also the x64 RyuJIT.

The x86 results are better, but JIT is still hefty:
```
BenchmarkDotNet=v0.10.3.0, OS=Microsoft Windows NT 6.2.9200.0
Processor=Intel(R) Core(TM) i7-4770K CPU 3.50GHz, ProcessorCount=8
Frequency=3421924 Hz, Resolution=292.2333 ns, Timer=TSC
  [Host]     : Clr 4.0.30319.42000, 32bit LegacyJIT-v4.6.1637.0
  DefaultJob : Clr 4.0.30319.42000, 32bit LegacyJIT-v4.6.1637.0


                  Method |            Mean |        StdDev |
------------------------ |---------------- |-------------- |
             JustCompile | 207,370.5465 ns | 1,948.6234 ns |
           CompileAndRun | 207,868.3895 ns | 1,507.1810 ns |
         JustFastCompile |  13,065.5246 ns |   101.2463 ns |
       FastCompileAndRun | 106,858.8770 ns |   970.2986 ns |
      PAssertWithCompile | 214,477.2560 ns | 1,505.0881 ns |
  PAssertWithFastCompile | 116,742.7924 ns |   297.4860 ns |
 BaseLinePlainLambdaExec |     108.5003 ns |     0.0993 ns |
```
