### ISSUE TITLE
Do not output subexpressions that don't have value available

### ISSUE THREAD

**Issue by lukas-lansky** [EamonNerbonne/ExpressionToCode#74]
First, thanks for a great tool!

Now, I tried this:

```
var a = new List<int> { 1, 2, 3, 3, 2, 1 };
PAssert.That(() => a.Count(e => e == 3) == 1);
```

The exception message looks like this:

```
assertion failed

a.Count(e => e == 3) == 1
                   e   →   
              e == 3   →   
                   a   →   {1, 2, 3, 3, 2, 1}
a.Count(e => e == 3)   →   2
```

I wonder if you thought about not outputting subexpressions without a value available, like in this case `e` and `e == 3`. It's clear there is nothing much to say about them as they change their value throughout the evaluation.

**Comment by EamonNerbonne** [comment]
Good catch! 

This way of displaying subexpressions is a little new (previously I tried to "point to" the right part), so this looks like a but or an oversight to me that was probably introduced then.

So either such expressions should simply not have value in the intermediate representation tree, or when that tree is serialized to this form, empty lines should be skipped.

I don't mind taking a stab at an improvement in this regard; but you want to then contributions are always welcome - what's your preference?

**Comment by EamonNerbonne** [comment]
BTW since I have your ear here anyhow - the top level expression `a.Count(e => e == 3) == 1` isn't explicitly annotated with `false`.  That was intentional, the motivation being that a failed assertion is implicitly false.  But sometimes this causes confusion.  Did this ever trip you up, even momentarily?  I'm considering treating the top-level expression no differently from other nodes.

**Comment by lukas-lansky** [comment]
If you don't mind, I'll try to look at it during this weekend.

Top-level expression absence didn't confuse me, I kind of like when the output is not too chatty (but provides everything important, of course). I understand your suspicion though -- if it were up to me, I would solve it by applying short description to the first line, in this case "assertion failed: 2 != 1". This would not be available in all cases (like when top-level method call just returns `false`), but in most cases it would give a very quick feedback that would be sufficient for interactive work when programmer probably knows what happening and does not need to dig into it too much.

**Comment by markijbema** [comment]
I would say that since this is meant for human consumption it might be worthwhile to optimize a few common cases. So I'd say a special case for x == y does not seem like a problem to me. Opinions @EamonNerbonne ?
