### ISSUE TITLE
Explicit control over generic type arguments representation

### ISSUE THREAD

**Issue by dadhi** [EamonNerbonne/ExpressionToCode#81]
It is more a question than an issue.

I have a strange problem in T4 template where suddenly the open-generic types started to include type parameter where they did not included before.

So instead of `typeof(A<>)` I am getting `typeof(A<T>)`.

I wonder if any way to control this thing explicitly?

More context:
I have an educated guess that something wrong with netstandard and System.Runtime in my setup with T4. I was previously getting error of ambigious reference to `System.Type`. 

I also know about the mess with changes in Reflection between the .Net versions. The `TypeInfo` introduced a split API for getting generic type arguments, two properties: `GenericTypeArguments` and `GenericTypeParameters`. The latter is aplicable for `GenericTypeDefinition`.  

Ultimately to diagnose my issue,  I would like to have a function `Func<Type, Type[]>` to inspect and may be override default behavior of getting the type arguments. Is it possible?

**Comment by EamonNerbonne** [comment]
I'm not sure I understand the issue;  do you have some kind of example?

So  if you had this....

```C#
void Main()
{
    ExpressionToCode.ToCode(()=> typeof(List<>)).Dump();
    Foo<int>.Bar().Dump();    
}

static class Foo<T>  {
    public static string Bar() => ExpressionToCode.ToCode(()=> typeof(List<T>));
}
```

You'd get
```
() => typeof(List<>)
() => typeof(List<int>)
```

And as far as I know that's about as good as it's feasible to do as `typeof` is converted to a `Constant` expression type, with value `typeof(List<int>)` without any reference to `T`.

So at least under some circumstances open generic types are serialized correctly - if you're seeing `T` that suggests there's something additional going on here...

**Comment by EamonNerbonne** [comment]
(For completeness, although I don't think the option is useful anymore, I also tried

```C#   
    ExpressionToCodeConfiguration.DefaultCodeGenConfiguration
        .WithAlwaysUseExplicitTypeArguments(true)
        .ToCode(()=> typeof(List<>)).Dump();
```
which also omits `T`

**Comment by dadhi** [comment]
I will try `WithAlwaysUseExplicitTypeArguments`, thanks. 

The problem is not the context. I mean it still outputs `typeof(<A<T>)` where it does not make sense. 

The problem is actually a mix of platform, runtime which breaks something, resulting in such behavior. That's why it is PITA

I will play suggested config and keep you posted

**Comment by EamonNerbonne** [comment]
I don't think `WithAlwaysUseExplicitTypeArguments` will actually help; I think it's an option that can disappear now (it was a workaround for the lack of overload resolution disambiguation in a previous version, but that's implemented now).  But it *is* a less "clever" code-path, so it might behave differently.

In any case, if you can reproduce the problem somehow, I don't mind looking in more detail!

**Comment by EamonNerbonne** [comment]
BTW which version of the package are you using?

**Comment by dadhi** [comment]
v1.5.4 ;)

**Comment by dadhi** [comment]
I need .Net 4.0

**Comment by EamonNerbonne** [comment]
Ah yeah; that's a known bug in 1.5.4; sorry!

**Comment by dadhi** [comment]
Really? that great cause I just need to update. Another reason to drop .NET 4.0 :)

**Comment by EamonNerbonne** [comment]
Yeah; I just took a peek; but .net 40 doesn't support `TypeInfo` (and fastexpessioncompiler), so it's not trivial to support both .net 4.0 and .net core in one codebase.  I'll check later if it's only a superficial issue.

**Comment by dadhi** [comment]
Everything works!!! Thanks, and sorry for bothering.

**Comment by dadhi** [comment]
You may consider to lower version from 452 to 45. Not every consuming library is bothering with minor versions :(
